@startuml
title A Game of Demesne
hide empty members
skinparam linetype ortho

note "Where is the concept of <b>Turn</b> here?" as TurnNote

note "Reevaluate whether these should actually be classes" as ClassNote

class Game {
  id: string
  stage: Stage
  turn: int
}

class Player {}

class Pile {
  faceup: bool
  countable: bool
  browseable: bool
}

together {
  class Deck
  class Discard
  class "Play Area"
  class Hand
}

together {
  class Supply
  class "Non-Supply"
  class Trash
}

together {
  class Base
  class Kingdom
}

together {
  class Pile
  class Card
}

note left of Game::stage
  Flesh out a more comprehensive notion of the current state
end note

Game *-- Supply
Game *-- "Non-Supply"
Game *-- Trash
Game *-- "2..6\n{ordered}" Player

Player -- "Play Area"
Player -- Hand
Player -- Deck
Player -- Discard

Deck *-- "1" Pile
Discard *-- "1" Pile

Trash .left. ClassNote
Supply .left. ClassNote
"Non-Supply" .left. ClassNote

Supply -- Base
Supply -- Kingdom

Base *-- "1.." Pile
Kingdom *-- "10.." Pile
"Non-Supply" *-- "1.." Pile

Trash *-- "1" Pile

Pile *-- "\r*\n{ordered}" Card

"Play Area" *-- "*" Card
Hand *-- "*" Card
@enduml
