@startuml
title How is a game of Demesne played?
skinparam hyperlinkColor black
skinparam hyperlinkUnderline false

!include sprites/uml.puml

<style>
partition {
  LineColor #33333333
  RoundCorner 25
}
</style>

start

floating note right #55000033
    Game setup as an activity in itself should probably be relegated
    to the application layer, or a service of some kind
end note

package "Application / Setup" {
	fork

	:Determine player count;

	:Setup Base Cards;

	fork again

	:Choose Kingdom Cards;

	fork again

	:Setup Trash;

	end fork

	note left
	     TODO: Clarify how setup and
	     choice-making will actually
	     be implemented
	end note

	note left
	     The specific size of
	     each ~~[[base-card-class.puml {Base Cards} Base Card]]~~ Pile
	     depends on the number
	     of players in the game
	     ====
	     TODO: Figure out a way
	     to document the pile sizes
	end note

	note right
	     Players collectively
	     select ten ~~[[kingdom-card-class.puml {Kingdom Cards} Kingdoms]]~~
	     to play with
	     ====
	     TODO: Flesh out how
	     this actually works
	end note

	note right
	     In the base game, the
	     ~~[[non-supply-class.puml {Non-Supply} Non-Supply]]~~ just
	     amounts to the ~~[[trash-pile-class.puml {Trash} Trash]]~~ pile
	end note
}

package "Game" {
    floating note
        This structure seems to entail that
        //a Game cannot be partially setup//,
        that is to say when a Game is created
        it must be done with complete information
        about the number of players and particular
        components involved
        ====
        It's not really clear that explicit
        stages are necessary here
    end note

    partition "Stage: Play" {
        :Deal decks;

        repeat
            :[[turn-activity.puml {How is a turn played?} Players take their turns <$subactivity_rake>]];
        repeat while () not ([End condition satisfied])
    }

    partition "Stage: Finished" {
        :Tally scores;
        :Determine victor;
    }
}

stop

@enduml
