@startuml
title How is a game of Demesne set up?
skinparam hyperlinkColor black
' skinparam hyperlinkUnderline false

<style>
partition {
  LineColor #33333333
  RoundCorner 25
}
</style>

start

fork

partition "Setup Supply" {
  :Setup Base Cards;

  :Choose Kingdom Cards;
}

fork again

partition "Setup Non-Supply" {
  :Setup Trash;
}

end fork

floating note left: The specific size of\neach [[base-card-class.puml {Base Cards} Base Card]] Pile\ndepends on the number\nof players in the game

floating note left: Players collectively\nselect ten [[kingdom-card-class.puml {Kingdom Cards} Kingdoms]]\nto play with



floating note right: In the base game, the\nNon-Supply basically\njust amounts to the\n[[trash-pile-class.puml {Trash} Trash]] pile. This changes\nin later expansions.

stop

@enduml
