@startuml
title How is a game of Demesne set up?
skinparam hyperlinkColor black
' skinparam hyperlinkUnderline false

<style>
partition {
  LineColor #33333333
  RoundCorner 25
}
</style>

start

fork

partition "Setup Supply" {
  :Setup Base Cards;
  note left
    The specific size of
    each [[base-card-class.puml {Base Cards} Base Card]] Pile
    depends on the number
    of players in the game
  end note

  :Choose Kingdom Cards;
  note left
    Players collectively
    select ten [[kingdom-card-class.puml {Kingdom Cards} Kingdoms]]
    to play with
  end note
}

fork again

partition "Setup Non-Supply" {
  :Setup Trash;
  note right
    In the base game, the
    Non-Supply basically
    just amounts to the
    [[trash-pile-class.puml {Trash} Trash]] pile. This changes
    in later expansions.
  end note
}

end fork

stop

@enduml
